# Call from other workflows:
#jobs:
#  call-security:
#    uses: vestfoldfylke/shared/.github/workflows/npm-security.yml@main
#    with:
#      audit_severity: "moderate" # required to be set. Can be one of (null, info, low, moderate, high, critical, none)
#      node_version: 22 # this one is optional and defaults to 22 if not set
#      package_path: "." # optional. Defaults to "." Usefull if you need to change the location of where package-lock.json resides
#

name: NPM security checks
on:
  workflow_call:
    inputs:
      audit_severity:
        required: true
        type: string
      node_version:
        required: false
        type: number
        default: 22
      package_path:
        required: false
        default: "."
        type: string

jobs:
  npm-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node ${{ inputs.node_version }} Environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.node_version }}

      - name: Resolve All Project Dependencies Using Npm (while ignoring scripts)
        working-directory: ${{ inputs.package_path }}
        run: npm ci --ignore-scripts

      - name: Run npm audit with severity ${{ inputs.audit_severity }}
        working-directory: ${{ inputs.package_path }}
        run: npm audit --omit=dev --audit-level=${{ inputs.audit_severity }}
