# Call from other workflows:
#jobs:
#  call-security:
#    uses: vestfoldfylke/shared/.github/workflows/npm-security.yml@main
#    with:
#      audit_severity: "moderate" # required to be set. Can be one of (null, info, low, moderate, high, critical, none)
#      node_version: 22 # this one is optional and defaults to 22 if not set
#

name: NPM security checks
on:
  workflow_call:
    inputs:
      audit_severity:
        required: true
        type: string
      node_version:
        required: false
        type: number
        default: 22
        
jobs:
  npm-audit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node ${{ inputs.node_version }} Environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ inputs.node_version }}

      - name: Resolve All Project Dependencies Using Npm (while ignoring scripts)
        run: npm ci --ignore-scripts
      
      - name: Run npm audit with severity ${{ inputs.audit_severity }}
        run: npm audit --omit=dev --audit-level=${{ inputs.audit_severity }}
