# Requires setup of trusted publisher before deploying. Read more: https://docs.npmjs.com/trusted-publishers and https://docs.npmjs.com/trusted-publishers
# All npm installations are run with --ignore-scripts, if you know that something is safe, and need it to run, set up a script in package.json called "safe-post-install", and run what you need.
#
# Call from other workflows:
# jobs:
#  publish-npm-package:
#    uses: vestfoldfylke/shared/.github/workflows/publish-npm-package.yml@main
#    with:
#      node_version: 24 # this one is optional and defaults to 24 if not set
#      audit_severity: "high" # this one is optional and defaults to "high" if not set. Can be one of (null, info, low, moderate, high, critical, none)
#

name: Publish NPM Package (Trusted publisher)
on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: number
        default: 24
      audit_severity:
        required: false
        type: string
        default: "high"
        
jobs:
  call-security:
    uses: vestfoldfylke/shared/.github/workflows/npm-security.yml@main
    with:
      audit_severity: ${{ inputs.audit_severity }}
      node_version: ${{ inputs.node_version }}

  build-and-deploy:
    needs: call-security
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC (trusted publisher setup)
      contents: read

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v6

      - name: Setup Node ${{ inputs.node_version }} Environment
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
      
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: "Resolve Project Dependencies Using Npm, Build and Test"
        shell: bash
        run: |
          npm ci --ignore-scripts
          npm run safe-post-install --if-present
          npm run build --if-present
          npm run test --if-present

      - name: "Publish to NPM"
        run: npm publish
